"""
Django settings for approve_me_please project.

Generated by 'django-admin startproject' using Django 1.9.dev20150122202547.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import socket
from unipath import FSPath as Path

# Project directory
BASE = Path(__file__).absolute().ancestor(2)
# Django code directory
BASE_CODE = Path(__file__).absolute().ancestor(1)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


PRODUCTION = True
if socket.gethostname() == 'rssrv2':
    PRODUCTION = False

if PRODUCTION:
    DEBUG = True
    #SITENAME = 'approve me please'
    #SITEDOMAIN = 'approve-me-please.com'
    SITEHOST = 'http://approve-me-please.com'
    MEDIA_URL = 'http://approve-me-please.com/media/'
else:
    DEBUG = True
    #SITENAME = 'approve me please'
    #SITEDOMAIN = 'approve-me-please.com'
    SITEHOST = 'http://192.168.1.11:8000'
    MEDIA_URL = 'http://192.168.1.11:8081/media/'



#MEDIA_ROOT = BASE.parent.child('media')
MEDIA_ROOT = BASE.child('media')


MEDIA_TEMP_DIRECTORY = '%s%s' % (BASE, '/temp/')
MEDIA_UPLOADS_DIRECTORY = '%s%s' % (BASE, '/uploads/')


#TATIC_ROOT = '%s/static/' % MEDIA_ROOT
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.7/howto/static-files/
#STATIC_URL = 'http://192.168.1.11:8081/static/'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


TEMPLATE_DIRS = [BASE.child('templates')]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE.child('templates')
        ],
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                #'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                #'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                #'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                # insert your TEMPLATE_LOADERS here
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]






# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.7/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1n0go@xw264v-bh7e@24$=(y2i7kc3r1k5kg*^v@8l6tv3c)f5'

# SECURITY WARNING: don't run with debug turned on in production!
#TEMPLATE_DEBUG = DEBUG

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    #'django.contrib.admin',
    #'django.contrib.auth',
    'django.contrib.contenttypes',
    #'django.contrib.sessions',
    'django.contrib.messages',
    #'django.contrib.staticfiles'
    'trunk.file',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    #'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'trunk.urls'

WSGI_APPLICATION = 'trunk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.7/ref/settings/#databases



# Internationalization
# https://docs.djangoproject.com/en/1.7/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

print '=== Hostname: %s' % socket.gethostname()
print '=== Production: %s' % PRODUCTION
print '=== Base Dir: %s' % BASE
print '=== Base Code Dir: %s' % BASE_CODE
print '=== Media Root: %s' % MEDIA_ROOT
print '=== Templates Dir: %s' % BASE.child('templates')